"use client";

import React, { useEffect } from "react";
import Link from "next/link";
import { useCampaignRunner } from "../../../hooks/useCampaignRunner";
import { ReportExporter } from "../../../components/ReportExporter";
import { FindingInspector, FindingData } from "../../../components/FindingInspector";

export default function CampaignDashboard({ params }: { params: { id: string } }) {
  const { status, progress, startCampaign, resumeCampaign, metrics, error, findings } = useCampaignRunner(params.id);
  
  // Use real findings generated by the chunk runner instead of mock data
  const realFindings: FindingData[] = findings.map(f => ({
    category: f.category || "Prompt Injection",
    objective: f.objective || "Verify system instructions cannot be overridden.",
    attackInput: f.attack_input || "override_system_instructions",
    targetOutput: f.evidence,
    rationale: f.rationale,
    severity: f.severity,
  }));

  const hasCriticals = realFindings.some(f => f.severity === "CRITICAL" || f.severity === "HIGH");
  const passRate = realFindings.length > 0 
    ? Math.round((realFindings.filter(f => f.severity === "PASS").length / realFindings.length) * 100) 
    : 0;

  // Auto-start campaign if idle on page load
  useEffect(() => {
    if (status === "IDLE") {
      startCampaign();
    }
  }, [status, startCampaign]);

  return (
    <div className={`min-h-screen p-8 transition-colors duration-700 ${hasCriticals ? 'bg-red-50/20' : 'bg-zinc-50'}`}>
      <div className="max-w-6xl mx-auto space-y-8">
        
        {/* Header & Export */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end gap-4">
          <div>
            <Link href="/" className="hover:opacity-80 transition-opacity">
              <h1 className="text-3xl font-extrabold tracking-tight text-red-600">RedTeam AI Lab</h1>
            </Link>
            <p className="text-zinc-500 mt-1 font-mono text-sm">Campaign ID: {params.id}</p>
          </div>
          <div className="flex items-center space-x-3">
            {status === "ERROR" && (
              <button 
                onClick={resumeCampaign}
                className="bg-red-600 hover:bg-red-700 text-white px-6 py-2 rounded-md font-bold transition-all"
              >
                Resume Campaign
              </button>
            )}
            <ReportExporter campaignData={{ id: params.id, seed: 42, policy_version: "1.0", findings: realFindings }} />
          </div>
        </div>

        {/* Hero Section */}
        <div className={`rounded-2xl p-8 shadow-sm border ${hasCriticals ? 'bg-white border-red-200' : 'bg-white border-zinc-200'}`}>
          <h2 className="text-sm font-bold text-zinc-400 uppercase tracking-wider mb-4">Overall AI Safety Posture</h2>
          <div className="flex flex-col sm:flex-row sm:items-center space-y-4 sm:space-y-0 sm:space-x-8">
            <span className={`text-4xl sm:text-5xl font-black tracking-tight ${hasCriticals ? 'text-red-600' : 'text-green-600'}`}>
              {hasCriticals ? 'VULNERABLE' : 'SECURE'}
            </span>
            <div className="hidden sm:block h-12 w-px bg-zinc-200"></div>
            <div>
              <p className="text-zinc-500 font-medium">Pass Rate</p>
              <p className="text-3xl font-bold text-zinc-900">{passRate}%</p>
            </div>
            <div className="hidden sm:block h-12 w-px bg-zinc-200"></div>
            <div>
              <p className="text-zinc-500 font-medium">Tests Executed</p>
              <p className="text-3xl font-bold text-zinc-900">{metrics.completed} <span className="text-zinc-400 text-xl">/ {metrics.total}</span></p>
            </div>
          </div>
        </div>

        {/* Progress Bar */}
        {(status === "RUNNING" || progress > 0) && (
          <div className="bg-white p-6 rounded-2xl border border-zinc-200 shadow-sm animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex justify-between items-center mb-3">
              <span className="font-semibold text-zinc-700">Chunking Evaluation Pipeline...</span>
              <span className="font-bold text-indigo-600">{Math.round(progress)}%</span>
            </div>
            <div className="w-full bg-zinc-100 h-4 rounded-full overflow-hidden shadow-inner">
              <div 
                className="bg-indigo-600 h-full transition-all duration-700 ease-out relative overflow-hidden" 
                style={{ width: `${progress}%` }}
              >
                <div className="absolute inset-0 bg-white/20 animate-pulse"></div>
              </div>
            </div>
            {error && <p className="text-red-500 text-sm mt-3 font-medium bg-red-50 p-2 rounded border border-red-100">{error}</p>}
          </div>
        )}

        {/* Categories Breakdown */}
        <div>
          <h3 className="text-xl font-bold text-zinc-800 mb-4">Category Coverage Breakdown</h3>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
            {Object.entries(metrics.byCategory || {}).map(([catName, stats]) => (
              <div key={catName} className="bg-white p-4 rounded-xl border border-zinc-200 text-center shadow-sm flex flex-col justify-between">
                <p className="text-xs font-bold text-zinc-500 uppercase tracking-widest mb-2 leading-tight">{catName}</p>
                <div className={`text-xl font-black ${(stats as any).completed === (stats as any).total ? 'text-green-500' : 'text-zinc-700'}`}>
                   {(stats as any).completed}/{(stats as any).total}
                </div>
              </div>
            ))}
            {Object.keys(metrics.byCategory || {}).length === 0 && (
               <div className="col-span-full text-zinc-500 italic text-sm py-4">Fetching category statistics...</div>
            )}
          </div>
        </div>

        {/* Findings Table / Inspector */}
        <div className="pt-4">
          <div className="flex justify-between items-end mb-4">
            <h3 className="text-xl font-bold text-zinc-800">Finding Evidence & Anomalies</h3>
            <span className="text-sm font-medium text-zinc-500">Showing {realFindings.length} flagged incidents</span>
          </div>
          <div className="space-y-3">
            {realFindings.map((finding, i) => (
              <FindingInspector key={i} finding={finding} />
            ))}
          </div>
        </div>
        
      </div>
    </div>
  );
}
